import { Repository } from "../../models/repository";

export const repositories: Repository[] = [
  {
    name: 'Ignews',
    description: 'Primeiro grande projeto realizado no curso Ignite da Rocketseat',
    tecnologies: ['FaunaDB', 'Jest', 'NextJs', "SASS", 'Prismic', 'Stripe', 'TypeScript'],
    linkGitHub: 'https://github.com/EduardoAraD/ignews',
  },
  {
    name: 'Portifolio',
    description: 'O repostório deste site.',
    tecnologies: ['Jest', 'NextJs', "SASS", 'TypeScript'],
    linkGitHub: 'https://github.com/EduardoAraD/portifolio',
  },
  {
    name: 'MarketSpace',
    description: 'MarketSpace é uma aplicação mobile de compra e venda de produtos novos ou usados.',
    tecnologies: ['Expo', 'Native Base', 'TypeScript'],
    linkGitHub: 'https://github.com/EduardoAraD/marketspace',
  },
  {
    name: 'Ignite Gym',
    description: 'Ignite Gym é um aplicativo de treino para academia.',
    tecnologies: ['Expo', 'Native Base', 'TypeScript'],
    linkGitHub: 'https://github.com/EduardoAraD/ignite-gym',
  },
  {
    name: 'Daily Diet',
    description: 'Daily Diet é uma aplicação mobile para controle da sua dieta',
    tecnologies: ['Expo', "Styled-Component", 'TypeScript'],
    linkGitHub: 'https://github.com/EduardoAraD/Daily_Diet',
  },
  {
    name: 'Ignite Teams',
    description: 'Ignite Teams é uma aplicação mobile de criação de times e gerenciar as pessoas',
    tecnologies: ['Expo', 'Styled-Component', 'TypeScript'],
    linkGitHub: 'https://github.com/EduardoAraD/igniteteams',
  },
  {
    name: 'Spacetime Backend',
    description: 'Spacetime é um projeto que registra momentos que você viveu na vida. A aplicação é dividida em 3 repositórios e este é o backend.',
    tecnologies: ['Fastify', 'Node', 'Prisma', 'TypeScript'],
    linkGitHub: 'https://github.com/EduardoAraD/BackendSpacetime',
  },
  {
    name: 'Spacetime Mobile',
    description: 'Spacetime é um projeto que registra momentos que você viveu na vida. A aplicação é dividida em 3 repositórios e este é o mobile.',
    tecnologies: ['Expo', 'TailwindCSS', 'TypeScript'],
    linkGitHub: 'https://github.com/EduardoAraD/MobileSpacetime',
  },
  {
    name: 'Spacetime Web',
    description: 'Spacetime é um projeto que registra momentos que você viveu na vida. A aplicação é dividida em 3 repositórios e este é o web.',
    tecnologies: ['NextJs', 'TailwindCSS', 'TypeScript'],
    linkGitHub: 'https://github.com/EduardoAraD/WebSpacetime',
  },
  {
    name: 'Feedback Widget Backend',
    description: 'Feedback Widget é um projeto de feedback que pode ser utilizado em qualquer site. Backend',
    tecnologies: ['Jest', 'Node', 'Prisma', 'TypeScript'],
    linkGitHub: 'https://github.com/EduardoAraD/Backend_NLW_Return',
  },
  {
    name: 'Feedback Widget Mobile',
    description: 'Feedback Widget é um projeto de feedback que pode ser utilizado em qualquer site. Mobile',
    tecnologies: ['Expo', 'TypeScript'],
    linkGitHub: 'https://github.com/EduardoAraD/Mobile_NLW_Return',
  },
  {
    name: 'Feedback Widget Web',
    description: 'Feedback Widget é um projeto de feedback que pode ser utilizado em qualquer site. Web',
    tecnologies: ['Vite', 'TailwindCSS', 'TypeScript'],
    linkGitHub: 'https://github.com/EduardoAraD/Web_NLW_Return',
  },
  {
    name: 'Gameplay',
    description: 'Gameplay é uma aplicação mobile para gerenciar grupos de amigos para diferentes jogos',
    tecnologies: ['Expo', 'TypeScript'],
    linkGitHub: 'https://github.com/EduardoAraD/gameplay-nlw',
  },
  {
    name: 'Pitaco App',
    description: 'Pitaco é uma aplicação mobile de pitacos de placares do brasileirão 2020. Mobile',
    tecnologies: ['React Native', 'Styled-Component', 'TypeScript'],
    linkGitHub: 'https://github.com/EduardoAraD/Pitaco_Mobile',
  },
  {
    name: 'Pitaco Backend',
    description: 'Pitaco é uma aplicação mobile de pitacos de placares do brasileirão 2020. Back-end',
    tecnologies: ['Node', 'TypeScript'],
    linkGitHub: 'https://github.com/EduardoAraD/backend-pitaco',
  },
  {
    name: 'Plant Manager',
    description: 'Plant Manager é uma aplicação mobile de gerenciamento de plantas',
    tecnologies: ['Expo', 'TypeScript'],
    linkGitHub: 'https://github.com/EduardoAraD/plantmanager/tree/main',
  },
  {
    name: 'Voz Perso',
    description: 'Voz Perso é uma aplicação mobile que response mensagens registradas.',
    tecnologies: ['React Native', 'TypeScript'],
    linkGitHub: 'https://github.com/EduardoAraD/VozPerso',
  },
  {
    name: 'Move It',
    description: 'Move It é uma aplicação web para pequenos exercicíos de alongamentos para devs.',
    tecnologies: ['CSS', 'NextJs', 'TypeScript'],
    linkGitHub: 'https://github.com/EduardoAraD/NLW_04_moveit_next',
  },
  {
    name: 'Happy Web',
    description: 'Happy é um projeto que gerencia visitas a orfanatos na sua cidade. Web',
    tecnologies: ['CSS', 'Maps', 'React JS'],
    linkGitHub: 'https://github.com/EduardoAraD/NLW_03_Web',
  },
  {
    name: 'Happy Mobile',
    description: 'Happy é um projeto que gerencia visitas a orfanatos na sua cidade. Mobile',
    tecnologies: ['Expo', 'Maps', 'TypeScript'],
    linkGitHub: 'https://github.com/EduardoAraD/NLW_03_Mobile',
  },
  {
    name: 'Happy Backend',
    description: 'Happy é um projeto que gerencia visitas a orfanatos na sua cidade. Backend',
    tecnologies: ['Node', 'TypeScript'],
    linkGitHub: 'https://github.com/EduardoAraD/NLW_03_backend',
  },
];
