import '../styles/global.scss';
import { Montserrat } from 'next/font/google'

import { Header } from '../components/Header';
import { Background } from '../components/Background';

const montserrat = Montserrat({
  weight: ['400', '700'],
  subsets: ['latin'],
  variable: '--font-montserrat',
})

export const metadata = {
  title: 'Edu Portifólio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Background>
          <Header />
          {children}
        </Background>
      </body>
    </html>
  )
}
